sr_core.a : scene.o gameobject.o entity.o 
	ar rcs sr_core.a scene.o gameobject.o entity.o 
	
scene.o : ../scene.cpp
	g++ -Wall -c ../scene.cpp 

gameobject.o : ../gameobject.cpp
	g++ -Wall -c ../gameobject.cpp

entity.o : ../entity.cpp
	g++ -Wall -c ../entity.cpp

ecar.o : ../ecar.cpp
	g++ -Wall -c ../ecar.cpp

