sr_camera.a : camera_base.o cameramanager.o
	ar rcs sr_camera.a camera_base.o cameramanager.o	
	
camera_base.o : camera_base.cpp
	g++ -Wall -c camera_base.cpp
	
cameramanager.o : cameramanager.cpp
	g++ -Wall -c cameramanager.cpp
	
