CC = g++
PROGRAM = streetracer
FLAGS = -Wall
LIBS = -lSDL2 -lGL -lGLU
PLIBS = ../camera/sr_camera.a ../math/sr_math.a 
SOURCES = main.cpp
ALL : $(SOURCES)
	$(CC) $(SOURCES) $(FLAGS) $(LIBS) $(PLIBS) -o $(PROGRAM)



